### ISSUE TITLE
gmapsdistance does not give different drive time results for different traffic models

### ISSUE THREAD

**Issue by ragram88** [rodazuero/gmapsdistance#42] opened 2018-07-13 15:05 UTC
Hi all,

I'm trying to get drive times for sets of origin latitude-longitude pairs, while taking traffic into account. However, I've tried different traffic models (best_guess, pessimistic, optimistic) with a specified departure time in the future but they all give me the same results. I also ran the rodazuero gmapsdistance function on just one origin and destination, and still got the same issue. 

I signed up for a free Google Cloud Platform trial and have an API key for the Google Distance Matrix API, so I should be able to use the traffic_model option in the gmapsdistance function. I wanted to see if there's a way for me to get the traffic_model option to work or if this is a bug with the gmapsdistance function that hasn't been fixed. Thanks for your help.

Thanks,
Raghav

**Comment by rodazuero** [comment] 2018-07-21 01:27
I *just* tried different traffic modes and it seems to be working fine. Can you provide a reproducible example? Are you sure you are setting up correctly the API key? How are you setting up the traffic options?

**Comment by ragram88** [comment] 2018-07-21 04:05
Hi Rodrigo,

Thanks for the prompt response. I was having trouble last week but it's
working fine now. I was previously using an older version of gmapsdistance,
but now I'm using version 3.4 and the traffic models give me different
drive times.

Thanks,
Raghav

**Comment by rodazuero** [comment] 2018-07-21 20:15
Ok, I'll go ahead and close this issue.

**Closed as completed by rodazuero** 2018-07-21 20:15 UTC
