### ISSUE TITLE
gmapdistanmatrix  don't consider the traffic jam, is it a bug?

### ISSUE THREAD

**Issue by qilingit** [rodazuero/gmapsdistance#32] opened 2017-12-06 15:19 UTC
Sorry for my English, I've setted the parameters `traffic_model = "pessimistic"` or `"best_guess"`, and the `dep_time, dep_date` are also different(for example: tuesday at 8:00 and sunday at 24:00), but always return the same result. Is it a bug?

**Comment by rodazuero** [comment] 2018-01-08 22:23
Can you provide an example? It might be the case that the traffic is the same. Try to run your query directly in google maps, the results using gmapsdistance should be the same.

**Comment by ghost** [comment] 2018-01-29 17:20
I have the same issue, tried many combinations with no luck, some example code here:

`results <- gmapsdistance(origin = c("Washington+DC", "New+York+NY"),
                         destination = c("Los+Angeles+CA", "Austin+TX"),
                         mode="driving", 
                         dep_date = "2018-01-31", 
                         dep_time = "21:40:00",
                         traffic_model = "pessimistic",
                         shape= "long",
                         combinations = "pairwise", 
                         key ="API_KEY")`

**Comment by Demetrio92** [comment] 2018-01-30 16:35
Guys, please make sure you have used `set.api.key(my_key)` before calling the function with `traffic_model`, otherwise gmaps API simply ignores it. 
If used correctly you should've run into the issue #31, which is being solved atm.

**Comment by SGBos** [comment] 2018-06-30 17:06
I have the same issue, and I do have an API key. The following code has two loops. One specifies departure date, time, and traffic mode. The other doesn't, but it returns the exact same travel times as the first (no increases due to rush hour traffic, even though some of the trips in the csv file are between suburban and city center addresses in major cities.) I confirmed in Google Maps that there should be large delays at the specific time I specified.

```
library(gmapsdistance)

set.api.key("My API key")

data <- read.csv("Addresses.csv", header = TRUE)
depth <- (nrow(data))
results = data.frame()

i <- 1
while (i < depth + 1) {

drivetime = gmapsdistance(origin = as.character(data$ADDRESS[i]),
					destination = as.character(data$DESTINATION[i]),
					mode = "driving",
			                dep_date = "2018-7-02",
				        traffic_model = "best_guess",
					dep_time = "8:00:00")

line = data.frame(data$YARDI[i], data$PROP_NAME[i], data$ADDRESS[i], data$DESTINATION[i], data$MSA[i], drivetime$Time)

results <- rbind(results, line)

i = i+1
}


#second loop, same results:

i <- 1
while (i < depth + 1) {

drivetime = gmapsdistance(origin = as.character(data$ADDRESS[i]),
					destination = as.character(data$DESTINATION[i]),
					mode = "driving")

line = data.frame(data$YARDI[i], data$PROP_NAME[i], data$ADDRESS[i], data$DESTINATION[i], data$MSA[i], drivetime$Time)

results <- rbind(results, line)

i = i+1
}

write.csv(results, file = "MyData8am.csv")
```

**Comment by SGBos** [comment] 2018-06-30 17:14
When I log into the Google Cloud platform, it show that I've been querying the Distance Matrix API when I run the code posted above. Is there some additional Google setting I need to enable to access the traffic delay info, or is this an issue with gmapsdistance?

Thanks!

**Comment by Demetrio92** [comment] 2018-06-30 18:55
@SGBos while I could test the issue on my data, can you please post a reproducible example without loops and imports of some data? 

In case you want to debug it yourself, `gmapsdistance` provides you a URL it shoots at the GMaps API. You can put the url into the browser and examine the output.

**Comment by SGBos** [comment] 2018-06-30 20:07
Thanks. If you want to test my code as is, you could try it on the following small csv:

```
YARDI,PROP_NAME,ADDRESS,MSA,DESTINATION
atl03902,Suwanee Creek 2 (atl03902),140+Satellite+Blvd.+Suwanee+GA,US-Atlanta,Atlanta+GA
atl02201,Breckenridge Bus Ctr 1 (atl02201),1925+Breckinridge+Plaza+Duluth+GA,US-Atlanta,Atlanta+GA
sba04703,D-Sunnyvale 8 (sba04703),380-382+Caribbean+Dr.+Sunnyvale+CA,US-SF Bay Area,San+Francisco+CA
sea04312,Seattle 12 (sea04312),3301+S+Norfolk+Street+Seattle+WA,US-Seattle,Seattle+WA
```

I found another way to do this using a Python package (googlemaps)...I was able to get the times in traffic no problem. So I think the issue is with gmapsdistance. I don't need to use it anymore, but figured people should be aware.

**Comment by tomershoham** [comment] 2018-07-03 10:07
I'm having the same problem.
I just ran a very simple loop, and I'm getting the same driving time (which is the no traffic scenario).
Looking at google maps it is not what I'm supposed to get.

t <- c("00:30:00", "01:30:00","02:30:00","03:30:00","04:30:00","05:30:00","06:30:00","07:30:00","08:30:00","09:30:00","10:30:00","11:30:00","12:30:00","13:30:00","14:30:00","15:30:00","16:30:00","17:30:00","18:30:00","19:30:00","20:30:00","21:30:00","22:30:00","23:30:00")
x <- c()
for (i in t){
  results_new = gmapsdistance(origin = "32.79405+34.98957",
                              destination = "32.0853+34.78177",
                              mode = "driving",
                              dep_date = "2018-07-04",
                              dep_time = i,
                              key = "mykey"
  x <- c(x,results_new$Time )
}

**Comment by Demetrio92** [comment] 2018-07-03 17:09
@tomershoham  @SGBos as you can see, this issue is still open and my PR fixing it (#35) is still not merged. The package version on CRAN is even worse, it just breaks on any attempt to calculate the distance with traffic. 
Which all points to one thing: this repository in unmaintained. please do: 
`devtools::install_github("demetrio92/gmapsdistance", ref='duration_fix')`, this should solve your issues. 
Feel free to fork and maintain, I'll gladly help with issues/PR/whatsoever. For now gmaps driving distance in R is not so crucial for me to maintain the package.

@tomershoham thx for a reproducible example, this helped! However, please take at least minimal effort to format your code if you want some help. You also forgot the closing bracket in the call to the `gmapsdistance`. 

Cheers

**Comment by qilingit** [comment] 2018-07-05 14:36
Hello, sorry guys, I've been very busy during this time, I've resolved this problem, and test for many times.

In fact, I've make the output with `JSON` format, and make it more detailed for the error messages. You can copy the code in : `https://github.com/qilingit/gmapsdistance`

I have not read solution of @Demetrio92 , but I think it's good.

**Comment by tomershoham** [comment] 2018-07-08 07:17
Thank you both @Demetrio92 @qilingit  very very much! it solved my problems.

@Demetrio92 I'm sorry for the wrong coding, just deleted my key and it appears that a bit more. 
that was my first massage here, I'll do my best to study the syntax.

greetings to you both!

**Comment by Demetrio92** [comment] 2018-07-09 20:08
Fixed!
`devtools::install_github("rodazuero/gmapsdistance")`
CRAN update coming soon

**Closed as completed by Demetrio92** 2018-07-09 20:08 UTC
